### PR TITLE
[REF] Implemented a brainstat package architecture

### PR DESCRIPTION
**Pull request by ReinderVosDeWael**
List of changes:
- Contents of surfstat moved to brainstat and/or trash
- Sandboxes moved to trash
- Reorganized brainstat submodules
- Removed (py_)SurfStat from all function and file names. 
- Replaced all current directory dependent relative paths with absolute paths derived from the package path.
- It is now a requirement for brainstat to be on the Python path. 
- Added a trash directory - my intention is to remove this before merging into master. I'm keeping it in the repository for now so it's easy to return files later if we decide we do want to keep them.

Discussion points
- The function names and module names are now identical, which can cause some problems with importing a module/function. I tried fixing this by adding function imports to __init__.py but this behavior seems to be somewhat inconsistent. I suggest we modify the module/function names but am not sure yet what we should rename them too. 
    - We're currently mostly using one function per file (very MATLABy ;-) ). We could probably merge several functions into greater modules (e.g. SurfStatP, SurfStatQ, SurfStatT, SurfStatLinMod?).
    - The removal of SurfStat from the function names makes some names a little odd e.g. `SurfStatP()` --> `P()`
    - The capitalization of the SurfStat functional is quite inconsistent with standard python capitalization
- I basically copied all SurfStat functions to the stats directory, but some functions feel misplaced here e.g. `SurfStatEdg`
- We're currently maintaining two MATLAB SurfStat version: A 'legacy/modified' version for Python testing and the new shiny BrainStat version. Any relevant changes to the Python version should be integrated into BrainStat and comparison tests should call new BrainStat.
- The remaining files in the surfstat directory need to be moved somewhere else or trashed. 

I'll leave this as a draft PR until we've resolved the major issues.

### CODE REVIEW

**Comment by sheyma** [comment]
Hi @ReinderVosDeWael ,

thanks a lot for this PR!

I like the general idea of restructuring the "python package directory", many thanks for your "Gehirn Kraft" here. 

However, to make the hard decisions such as `SurfStatP()` vs `P()` easier to discuss, it could be better to divide this PR into 2 or 3 separate ones:

1. Let's remove the "dead" code completely. IMO, we should remove any piece of code that we don't use at all. This would reduce the noise in the upcoming restructuring patches. Below is a potential list of dir's to be removed without introducing another trash dir:

master/surfstat/python/need_not_convert
master/matlab_sandbox
master/python
master/python_sandbox

Let's use the beauty in git: We can always find things in the history if any piece of removed code is needed.

Afterwards, we can discuss the rest below.

2. restructuring the dirs
Personally I would like to have a `brainstat/` package directory with python code only, according to the recommend way [here](https://docs.python.org/3/tutorial/modules.html#packages)
3. renaming the functions

**Comment by ReinderVosDeWael** [comment]
Mhm if I had thought of making the refactoring separate PRs from the start that might've been a good idea, however I splitting this up now may be a lot more work than it's worth. The fastest way would probably be to discard this entire PR and start again from scratch - but given that most of the work is already done that seems wasteful. The remaining things that need to be finished up for this PR to be mergeable are all relatively small changes compared to what's already been done. 

To address specific points: 

> Let's remove the "dead" code completely. IMO, we should remove any piece of code that we don't use at all. This would reduce the noise in the upcoming restructuring patches. Below is a potential list of dir's to be removed without introducing another trash dir:

I agree in the long term, on the short term (i.e. before merging to master) I had intended that this is more of a bookkeeping directory. I figured it'd make it a lot more transparent for all of you to see what exactly I intend to delete. If you prefer then I can just `git rm` the entire thing now though

> master/surfstat/python/need_not_convert
> master/matlab_sandbox
> master/python
> master/python_sandbox

These are already in the trash pending deletion (https://github.com/MICA-MNI/BrainStat/tree/refactor/trash).

>  restructuring the dirs
> Personally I would like to have a brainstat/ package directory with python code only, according to the recommend way here

This is already included (https://github.com/MICA-MNI/BrainStat/tree/refactor/brainstat) . Although as mentioned before I think we can improve upon the 1 file 1 function structure we are using now. 

> renaming the functions

This goes hand-in-hand with the restructuring the dirs point - how we restructure our directory/file/function names seems like sides of the same coin to me i.e. I wouldn't separate these two issues.

**Comment by ReinderVosDeWael** [comment]
Also, I've added (temporary) placeholder files in a few directories. I only just noticed that Git doesn't upload empty directories. Same as with the late trash directory, I'm putting this up solely for clarity when inspecting the changes i.e. I intend to delete these files before changing this PR from a draft to a real PR

**Comment by ReinderVosDeWael** [comment]
Have posted this in slack, but including here for posterity A directory/function name suggestion image

**Comment by sheyma** [comment]
Hi @ReinderVosDeWael ,

creating & deleting directories and renaming functions are quite invasive changes. Unfortunately, I have difficulty reviewing such big changes + loose my orientation in the project. However, really appreciate this PR as a good base of dicsussion. 

I see your point of not wanting to loose already done work of yours (I can still cry about need-not-to-convert :) ). Still, we can minimize this PR and merge it. 

Here are my suggestions for this PR:

1. function renaming should be re-discussed.
For now, I would vote for keeping the names as they are, ie. SurfStatP.py. 

2. do not create "placeholder" dirs, instead, create dirs only if they have already meaningful _content_.
I am not (completely) against having dirs like **io**, **vis** in future, but please not before having at least some living code in it.

1. & 2. together would mean the structure below.

BrainStat/brainstat/stats/SurfStatP.py
BrainStat/brainstat/stats/SurfStatEdg.py
[...]
BrainStat/brainstat/tests

3. brainstat dir should only have python code inside, as in consistency with your figure above. Therefore, /brainstat/utils/ is debatable, because it contains matlab code. Also, as long as we have only one dir (**stats**) using the **utils** code, we don't need to generate a shared **utils**. We can add a shared utils later, if there is a need for it, for instance, when a new subdir context is created and if it needs **utils** code. 

Regarding the matlab code needed for online testing, how about moving it to a toplevel "contrib" or "ext" dir? Example:

BrainStat/ext/surfstat_matlab
or
BrainStat/contrib/surfstat_mabtlab .

Cheers!

**Comment by ReinderVosDeWael** [comment]
Changed the function names back to SurfStat*. 

Regarding the MATLAB code inside brainstat, as is mentioned in the opening post, I think this entire version should be removed at some point and its functionality subsumed by the already existing matlab directory. However, that seems like outside of the scope of this PR hence I left it in for now -- unless you want me to make this PR even bigger :). 

Regarding the other contents of the utils directory (matlab_functions, utils.fetch_tutorial_data, deprecated): these functionalities don't have other obvious places where they should go for the moment. I've renamed the directory to unassigned to indicate that the location of its contents is undecided.

**Comment by sheyma** [comment]
Hi @ReinderVosDeWael ,

> Changed the function names back to SurfStat*.

That's great!

> Regarding the MATLAB code inside brainstat, I don't see why we need two versions. I think this entire version should be removed at some point and its functionality subsumed by the already existing matlab directory.

Totally agreed! Let's aim for moving all code in **/BrainStat/brainstat/unassigned/matlab/*** into **/BrainStat/matlab/.** in another PR.

(Remember, in the past, we had two goals: 1) python conversion of surfstat, 2) updating surfstat. To prevent any conflict, which could happen while multiple people working on both 1) and 2), we had created two matlab dirs. Now, having completed goal 1), we can aim for having a single matlab dir.)

Two minor comments:

I'd recommend to move /BrainStat/brainstat/**matlab_functions.py** and /BrainStat/brainstat/**utils.py**  into /BrainStat/brainstat/stats/. Because they are only needed there. If they are needed somewhere outside of /BrainStat/brainstat/stats/ in future, we can still remove them into a utils dir.

Maybe also remove the directory /BrainStat/brainstat/context, as long as it has no content. 

I'd be very happy to merge this PR into master (once travis gives the green light) soon. It is a painful PR, but at the end we will have a minimalistic structure to work on. 

Thanks a lot!

**Comment by ReinderVosDeWael** [comment]
Implemented all the suggested changes. 

Travis is taking a long time to start, but my local flake8 ran without warnings/errors, and the tests run without error. I'll change this PR from a draft to a regular PR. 

Assuming Travis comes back without error or, in case it doesn't run, a local flake8 run returns without error for someone else then I think this PR is ready for merging.

**Comment by sheyma** [comment]
Awesome!

**Pull request merged**
