### PR TITLE
Tutor v2

### PR DESCRIPTION
**Pull request by sheyma**

### CODE REVIEW

**Comment by sheyma** [comment]
Hi, 
this is also another not-must PR.

`tutor_v2` includes an ipython notebook illustrating a very simple use case of brainstat in consistency with:

[SURFSTAT_2017.pdf](https://github.com/MICA-MNI/micaopen/blob/master/surfstat/surfstat_tutorial/SURFSTAT_2017.pdf)

Maybe it helps building a tutorial for the OHBM abstract.

Downside: it depends on `vis` branch.

Best.

**Comment by ReinderVosDeWael** [comment]
Won't have time to look at this in detail today - but for the tutorials I recommend we follow the sphinx gen_gallery layout as this integrates nicely with ReadTheDocs e.g. see https://github.com/MICA-LAB/BrainStat/blob/python_tutorial/docs/python/tutorials/plot_tutorial_01_basics.py and the resultant documentation with downloadable .py and .ipynb files https://brainstat.readthedocs.io/en/python_tutorial/python/generated_tutorials/plot_tutorial_01_basics.html#sphx-glr-python-generated-tutorials-plot-tutorial-01-basics-py.

**Comment by sheyma** [comment]
no worries, that's not an urgent PR.
All right, I will study what you mean by sphinx gen_gallery.

**Comment by sheyma** [comment]
aha, ok, it might be better if only one person continues with [tutorial and its docs](https://brainstat.readthedocs.io/en/python_tutorial/python/generated_tutorials/plot_tutorial_01_basics.html#sphx-glr-python-generated-tutorials-plot-tutorial-01-basics-py). 

Independent of sphinx gen_gallery, what matters the most is the content of tutorial. There we have two different approaches.

`tutor_v2` uses thickness data of shape 20k and plot across fsaverage 20k, independent of brainspace.
`python_tutorial` uses random data of shape 32k, which fits nicely with conte69, dependent on brainspace.

Both approaches seem equally nice to me, since they both have +/- sides. 

Therefore, feel free to choose whichever approach you want to continue.

Ideally, it would be great, if the tutorial reflects findings in the abstract. But it is not in a hurry now.

**Comment by ReinderVosDeWael** [comment]
Alright I finally had time to look at the .iypnb. I'll bring some of the code over to the Python tutorial branch in due time. One overall comment on the tutorial style: these tutorials should be written for people who aren't good at statistics or programming. What I mean by that is that we should spend a lot of time explaining what we're doing and then the code should follow logically from those explanations.. For example, the section below will only really be accessible for someone who is already familiar with SurfStat/

```
# get the AGE 
AGE = np.array(a['demographics']['AGE'])

# code some variables of interest
AGE_term = Term(AGE)

# build a model
M = 1 + AGE_term

# estimate the model parameter slm
slm = linear_model(thickness, M, SW); 

# specify the contrast
slm = t_test(slm, -AGE)
```

**Comment by sofievalk** [comment]
Ha - yes I can edit this?

**Comment by ReinderVosDeWael** [comment]
@sofievalk can you hold off until after our meeting so we don't have three parallel tutorial implementations? :p

**Comment by ReinderVosDeWael** [comment]
Closing as this has already been incorporated into the existing tutorial.

**Pull request closed without merging**
