### PR TITLE
[TST] MATLAB unit tests

### PR DESCRIPTION
**Pull request by ReinderVosDeWael**
PR adds MATLAB unit tests based on the Python unit tests, removes the Azure dependency, and reimplemented MATLAB CI with Github Actions.

### CODE REVIEW

**Comment by ReinderVosDeWael** [comment]
PR is ready for review & merging @sheyma

**Comment by ReinderVosDeWael** [comment]
Made an additional change to how the unit tests are run: the Azure dependency has been removed and all CI (including MATLAB) is now run through Github

**Comment by ReinderVosDeWael** [comment]
Updated the README.rst badges as well now.

**Comment by sheyma** [comment]
Hi,
nice PR!

Could you please share the command to run [matlab unittests](https://github.com/MICA-MNI/BrainStat/blob/matlab_unittests/brainstat_matlab/tests/%40test_precomputed/test_precomputed.m) locally?

Minor suggestions:

- is it possible to add older python versions here in [*.yml](https://github.com/MICA-MNI/BrainStat/blob/matlab_unittests/.github/workflows/MATLAB_unittests.yml), the ones mentioned in python CI? (I don't have python 3.8)

- could you maybe add original surfstat function names as comments inside the [test functions](https://github.com/MICA-MNI/BrainStat/blob/matlab_unittests/brainstat_matlab/tests/%40test_precomputed/test_precomputed.m), as you did already for some of them? 

- not sure if the test for "SurfStatPeakClus" was implemented (maybe it will be clear after the point above).

- we might need to change pickle names for 'linmod' to 'xlinmod' later, so that all would work with PR #110 (I can do it after this PR first merged). 

Best!

**Comment by ReinderVosDeWael** [comment]
To run one tests you can use the run function of the testCase class e.g. `run(test_precomputed)`. If you want to keep the testing object use `test = test_precomputed; test.run` instead. Note that your MATLAB needs to be coupled with a python environment that has numpy installed (see `pyenv`). Also, the test data must be available on your local computer. 

I'd not rerun the tests with other Python versions; Python is used only to load the .pkl files. Loading .pkl files is already tested with all Python versions in our Python Unit Tests, so there's no need to run all MATLAB tests thrice with different Python environments. 

SurfStatPeakClus is in there (test_peakclus) but the comment inside is wrong - I'll modify that and add all the other function names as suggested. 

Regarding the name change, that should be simple to modify once we're satisfied with the new unit test data.

**Comment by ReinderVosDeWael** [comment]
Also, if you want to run all tests you can do so as follows:
```
tests = testsuite('/Path/to/BrainStat/brainstat_matlab/tests');
tests.run
```

**Comment by ReinderVosDeWael** [comment]
Comments added as suggested @sheyma

**Comment by sheyma** [comment]
Thanks for adding comments, it made it super helpful!

It was a cool idea that we use now python unit test data also data for matlab! I am going to merge this PR into master in a sec, but, would like to put some of my thoughts here. 

There is maybe a lesson to learn: Using different languages, it would have been the best to decide for a test data format, that is accepted by both languages, ie hdf5, txt, ...

Because now matlab unittests are depending on python, and this is only for data read-in.

Worse than that, this dependency is limited to [python 2.7, 3.7, 3.8](https://www.mathworks.com/help/matlab/matlab_external/install-supported-python-implementation.html).

I could run it as below:

```
$ conda create --name test38 python=3.8
$ cd /BrainStat/brainstat_matlab/tests
$ matlab -nodesktop
>> pyversion('/pathToThere/anaconda2/envs/test38/bin/python')
>> addpath(genpath('/BrainStat/brainstat_matlab/stats'))
>> run(test_precomputed)
```

Finishing with a good thing: all of your tests run successfully, thanks!

**Pull request merged**
