### PR TITLE
Datagen mesh edges

### PR DESCRIPTION
**Pull request by sheyma**
Hi,
this PR generates the test data for [test_mesh_edges.py](https://github.com/MICA-MNI/BrainStat/blob/master/brainstat/tests/test_mesh_edges.py).

### CODE REVIEW

**Review by ReinderVosDeWael — COMMENTED** [review]
Could you add comments on what each test consist of in datagen_mesh_edges? Simply copying this over from test_mesh_edges.py could suffice. That'll make any modifications later on a lot simpler.

**Comment by sheyma** [comment]
sure, done!

**Comment by ReinderVosDeWael** [comment]
I suggest we change pickle protocol from HIGHEST_PROTOCOL (=protocol 5) to 4. Protocol 5 was introduced in Python3.8. So if the data is generated on Python3.7 this will default to protocol 4, whereas if its generated on Python3.8 it'll be protocol 5 (and unreadable on older versions!). 

Protocol 4 was added in Python 3.4 so it will be compatible with all supported versions of BrainStat. Other than that it looks good.

**Comment by ReinderVosDeWael** [comment]
Note: I'd implement the highest protocol comment in other datagens too.

**Pull request merged**
