### PR TITLE
Bugs an dtests

### PR DESCRIPTION
**Pull request by sheyma**
Hi all, 

we have now advanced tests with real data for comparing matlab-python output equality.

However, there have been two bug cases, that I could not fix:

* test_20 in **test_SurfStatP.py** 

Inequality is probably coming from from **stat_threshold** function in [**SurfStatP.py**](https://github.com/MICA-MNI/BrainStat/blob/bugsANDtests/surfstat/python/SurfStatP.py#L112-L118)

* test_11 in  **test_SurfStatF.py** 

Any help is appreciated!

### CODE REVIEW

**Comment by ReinderVosDeWael** [comment]
Will have a look at these today.

**Comment by ReinderVosDeWael** [comment]
I can't reproduce an error in SurfStatP test 20 - it passes for me across several runs. The error in SurfStatF seems to be due to a quirk in Numpy's order of operations. It prioritizes multiplication over division rather than run them left-to-right, whereas MATLAB follows the more conventional order of operations.

**Comment by ReinderVosDeWael** [comment]
Scratch that - I couldn't believe Numpy could get something as basic as BEMDAS wrong so I had another look. The error was simply wrongly placed brackets.

**Comment by sheyma** [comment]
Nice catch in SurfStatF.py! Maybe I had taken care of BEMDAS more carefully there.
Now, all tests in **test_SurfStatF.py** are running successfully.

I still have the failure in test_20 of **test_SurfStatP.py**

```
============================================================== short test summary info 
FAILED tests/test_SurfStatP.py::test_20 - assert False
========================================== 1 failed, 19 passed, 1 skipped, 3 warnings in 585.50s (0:09:45) ==========================================
```

**Comment by ReinderVosDeWael** [comment]
No errors here

```
(academic) [Mon Nov 23 14:32] reinder@io: ~/GitHub/BrainStat/surfstat
$ python3 -m pytest -s tests/test_SurfStatP.py  -k test_20
============================= test session starts ==============================
platform darwin -- Python 3.7.9, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /Users/reinder/GitHub/BrainStat/surfstat/tests, configfile: pytest.ini
collected 21 items / 20 deselected / 1 selected

tests/test_SurfStatP.py .

=============================== warnings summary ===============================
test_SurfStatP.py::test_20
  python/SurfStatT.py:84: UserWarning: Contrast is not in the model :-(
    warnings.warn('Contrast is not in the model :-( ')

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================= 1 passed, 20 deselected, 1 warning in 13.94s =================
```

**Comment by sheyma** [comment]
wait, I will rebase this branch on top of master and run the tests again.
If the issue with test_20 persists, then maybe we have different environments (ie. our numpy versions etc.)

**Comment by sheyma** [comment]
Error in test_20 persists.
Are you using a conda environment? If yes, could I get that? Maybe we have different versions of packages.

**Comment by ReinderVosDeWael** [comment]
Et voila. Save this as a .yml file and use `conda env create -f environment.yml` to install it
 

```
name: academic
channels:
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=20.1.0=py37haf1e3a3_1
  - async_generator=1.10=py37h28b3542_0
  - attrs=20.2.0=py_0
  - backcall=0.2.0=py_0
  - bleach=3.2.1=py_0
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py37h2987424_2
  - cffi=1.14.3=py37hed5b41f_0
  - cycler=0.10.0=py_2
  - dbus=1.13.18=h18a8e69_0
  - decorator=4.4.2=py_0
  - expat=2.2.10=hb1e8313_2
  - freetype=2.10.4=h3f75d11_0
  - gettext=0.19.8.1=hb0f4f8b_2
  - glib=2.66.1=h9bbe63b_0
  - icu=58.2=h0a44026_3
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.18.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_1
  - jedi=0.17.2=py37_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=he5867d9_2
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_core=4.6.3=py37_0
  - jupyter_nbextensions_configurator=0.4.1=py37hc8dfbb8_2
  - jupyterlab_pygments=0.1.2=py_0
  - kiwisolver=1.3.0=py37h23ab428_0
  - lesscpy=0.13.0=py_1
  - libblas=3.9.0=2_openblas
  - libcblas=3.9.0=2_openblas
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=5.0.0=h7cc5361_13
  - libgfortran5=9.3.0=h7cc5361_13
  - libiconv=1.16=h1de35cc_0
  - liblapack=3.9.0=2_openblas
  - libopenblas=0.3.12=openmp_h54245bb_1
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.18=h1de35cc_0
  - llvm-openmp=11.0.0=h73239a0_1
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib-base=3.2.2=py37hddda452_1
  - mistune=0.8.4=py37h1de35cc_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py37_0
  - nbformat=5.0.8=py_0
  - ncurses=6.2=h0a44026_1
  - notebook=6.1.4=py37_0
  - numpy=1.19.2=py37h91c9966_1
  - openssl=1.1.1h=haf1e3a3_0
  - packaging=20.4=py_0
  - pandoc=2.11=h0dc7051_0
  - pcre=8.44=hb1e8313_0
  - pexpect=4.8.0=py37_0
  - pip=20.2.4=py37_0
  - ply=3.11=py_1
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.8=py_0
  - prompt_toolkit=3.0.8=0
  - pycparser=2.20=py_2
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h655552a_2
  - pyrsistent=0.17.3=py37haf1e3a3_0
  - python=3.7.9=h26836e1_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pyyaml=5.3.1=py37h395d20d_1
  - qt=5.9.7=h468cd18_1
  - qtconsole=4.7.7=py_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h1de35cc_0
  - setuptools=50.3.0=py37h0dc7051_1
  - sip=4.19.8=py37h0a44026_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=hffcf06c_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hb0a8c7a_0
  - tornado=6.0.4=py37h1de35cc_1
  - traitlets=5.0.5=py_0
  - wcwidth=0.2.5=py_0
  - wheel=0.35.1=py_0
  - widgetsnbextension=3.5.1=py37_0
  - xz=5.2.5=h1de35cc_0
  - yaml=0.2.5=haf1e3a3_0
  - zeromq=4.3.3=hb1e8313_3
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - appdirs==1.4.4
    - appnope==0.1.0
    - black==18.6b4
    - brainspace==0.1.1
    - chardet==3.0.4
    - ci-info==0.2.0
    - click==7.1.2
    - cython==0.29.21
    - defusedxml==0.6.0
    - entrypoints==0.3
    - etelemetry==0.2.2
    - filelock==3.0.12
    - flake8==3.8.4
    - idna==2.10
    - iniconfig==1.1.1
    - ipython-genutils==0.2.0
    - isodate==0.6.0
    - joblib==0.17.0
    - json5==0.9.5
    - jupyterlab==2.2.9
    - jupyterlab-server==1.2.0
    - lxml==4.6.1
    - matlab-kernel==0.16.10
    - matlabengineforpython==R2018a
    - matplotlib==3.3.2
    - mccabe==0.6.1
    - metakernel==0.27.1
    - mtspec==0.3.2
    - nest-asyncio==1.4.2
    - networkx==2.5
    - nibabel==3.2.0
    - nilearn==0.7.0
    - nipype==1.5.1
    - nose==1.3.7
    - numpy-groupies==0.9.13
    - optional-django==0.1.0
    - pandas==1.1.3
    - pandocfilters==1.4.3
    - parso==0.7.1
    - pickleshare==0.7.5
    - pillow==8.0.1
    - plotly==4.12.0
    - pluggy==0.13.1
    - prov==2.0.0
    - psutil==5.7.3
    - ptyprocess==0.6.0
    - py==1.9.0
    - pycodestyle==2.6.0
    - pycwt==0.3.0a22
    - pydot==1.4.1
    - pydotplus==2.0.2
    - pyflakes==2.2.0
    - pygments==2.7.2
    - pytest==6.1.2
    - pytz==2020.1
    - pyzmq==19.0.2
    - rdflib==5.0.0
    - requests==2.24.0
    - retrying==1.3.3
    - rise==5.7.1
    - scikit-learn==0.22.2
    - scipy==1.5.3
    - seaborn==0.11.0
    - send2trash==1.5.0
    - simplejson==3.17.2
    - skggm==0.2.8
    - sklearn==0.0
    - tabulate==0.7.5
    - terminado==0.9.1
    - threadpoolctl==2.1.0
    - toml==0.10.1
    - tqdm==4.51.0
    - traits==6.1.1
    - urllib3==1.25.11
    - vtk==9.0.1
    - webencodings==0.5.1
    - wurlitzer==2.0.1
    - zipp==3.4.0
prefix: /Applications/miniconda2/envs/academic
```

**Comment by sheyma** [comment]
All right, it looks like this issue requires a deeper investigation. 
Let's merge this PR into master, and I will open a bug issue for test_20.

**Pull request merged**
