### PR TITLE
[TST] data generation for random_field_theory

### PR DESCRIPTION
**Pull request by ReinderVosDeWael**
There we go. There were quite a few superfluous tests and tests with non-sensical data in the old version so I've modified the tests to be a bit more targeted. Current tests are as follows:

- Tests that modify variable types, specifically set slm.k and slm.df to unsigned integers.
- Tests that modify the optional variables used, particularly the inclusion (in all combinations) of 'dfs', 'cluster_threshold', 'mask', and 'k'. 
- A single test with nonsense variables in the SLM. 

I'm using the sklearn ParameterGrid framework here which makes finding the specific input to a single test a bit more work, but vastly improves the flexibility of our tests and automatically tests over all possible permutations of the inputs i.e. bugs due to interaction effects will be found. 

All output data has passed the MATLAB unit tests on my local device.

### CODE REVIEW

**Comment by sheyma** [comment]
Excellent test function! This was very inspiring.

The line below gives me an error:

`
$  python datagen_random_field_theory.py`


```
Traceback (most recent call last):
  File "datagen_random_field_theory.py", line 11, in <module>
    from brainstat.tests.testutil import generate_slm, save_slm, datadir
ImportError: cannot import name 'generate_slm'
```

Instead, replacing the corresponding erroneous line with this works well:
`from testutil import generate_slm, save_slm, datadir
`

Did you get similar issue?

**Comment by sheyma** [comment]
Also, I uploaded the generated data in this branch, namely` /extern/test-data/xstatp_*` , to [here](https://github.com/MICA-MNI/BrainStat/tree/test-data/extern/test-data).

**Comment by ReinderVosDeWael** [comment]
Weird - I can reproduce the error from my terminal, but not from the terminal inside Visual Studio Code. Both are running the same python environment from the same directory. I'm not sure I like the proposed fix as this would conflict for anyone who has an actual package called `testutil` in their environment. 

Let me have a look at a fix.

**Comment by ReinderVosDeWael** [comment]
Actually scratch what I said before - I made a dumb mistake (running the wrong file, getting a similar looking error and reading it as if it were the same error) in trying to reproduce this. 

No I can't reproduce your error. `python datagen_random_field_theory.py` runs for me without issue. I suspect your Python is sourcing brainstat from a different directory than the Github version. When you attempt to import `generate_slm`, which doesn't exist in the version you're using, it throws an error.

**Comment by sheyma** [comment]
Alright, knowing that you could not reproduce the error, I am merging it now.
I will check my erroneous case later in detail.
Cheers!

**Pull request merged**
