### PR TITLE
[WIP] Started converting term to Python

### PR DESCRIPTION
**Pull request by ReinderVosDeWael**
I was getting into the nitty/gritty of the MATLAB term/random classes so I figured I might as well use the newfound knowledge to start the Python classes. I'll keep the branch separate for now but anyone can feel free to jump in and help with the conversion. Currently only a very basic term class and the overloaded addition, subtraction, and multiplication methods are implemented. Also included is a .ipynb file containing a simple test for the addition and subtraction methods.

### CODE REVIEW

**Comment by sheyma** [comment]
Great to see your work on `@random` and `@term` classes!

In my other PR #8, I had skipped these classes for now. I would recommend to merge my PR first. Then you could rebase yours on top of mine. So we could adapt my `SurfStatLinMod` interface to make use of your provided  `@random` and `@term` classes.

Hope it makes sense to you, 
cheers!

**Comment by OualidBenkarim** [comment]
Great Reinder! I'm going to follow on the term and random classes

**Comment by sheyma** [comment]
Hi Reinder,

apologies for my super late review!

Since I am not experienced with object-oriented programming, I would need a bit of your help here.

1. Could you please rebase your patch on top of the master branch?
2. Can you maybe integrate `term` into SurfStatLinMod.py?

This would be the best for me to understand how to use `term` and how it works.

Thanks in advance,
Şeyma

**Comment by ReinderVosDeWael** [comment]
1. Merged master into this PR. 

2. @OualidBenkarim were you working on this already by any chance? If not I'll have a look.

**Comment by sheyma** [comment]
Danke!

**Pull request merged**
