### PR TITLE
small fix to CONTRIBUTING.rst

### PR DESCRIPTION
**Pull request by PeerHerholz**
- renamed `BrainSpace` to `BrainStat`
- fix link pointing to issues

### CODE REVIEW

**Comment by ReinderVosDeWael** [comment]
Just checked out the changes - looks good and ready for merging to me. I had copied this from a draft for BrainSpace a while back as an example to modify later and then forgot about the modification step :P. Also fixed the link to your issues page in the BrainSpace contributor guide draft as well.

**Comment by sheyma** [comment]
Yo! Can you correct my name to "Şeyma Bayrak" on developers list. Thanks :+1:

**Comment by MICA-MNI** [comment]
Not sure I get the Ş to work - I failed miserably

**Comment by sheyma** [comment]
then, I will deal with that later. Thanks Boris!

**Comment by ReinderVosDeWael** [comment]
@MICA-MNI @sheyma you're referring to the master branch, right? Not changes Peer made in this branch? If yes, I was curious how to add special characters in restructuredtext so I just fixed sheyma's name in the index.

**Comment by ReinderVosDeWael** [comment]
Also, @sheyma if this wasn't referring to the current PR could you merge the PR or let me/Peer know it's OK to merge?

**Comment by sheyma** [comment]
ooops, I was to late to see it all! Nice work people, thanks!

**Pull request merged**
