### PR TITLE
[ENH] First stage of SLM class

### PR DESCRIPTION
**Pull request by ReinderVosDeWael**
This PR adds the first version of a MATLAB SLM class equivalent to the Python implementation. I've purposefully left some to-do's out of this PR to keep the size of this PR as manageable as possible (it's already humongous). Note that this PR is based on the matlab_unittests branch and I recommend we merge that one before merging this. 

Usage is equivalent to Python i.e.
```MATLAB
slm = SLM(model, contrast, varargin);
slm.fit(Y);
```

Changes in this PR:
- Added the MATLAB SLM class.
- Removed all the SurfStat functions that are now part of the SLM class. 
- Added a package, brainstat_utils, for utility functions. 
- Modified the unit tests to use the SLM class. 

To-do in future PRs:
- Build MATLAB/Python synchronized SLM class tests.
- Add documentation (I've left this out as I want to look into automated API building on ReadTheDocs for MATLAB code)
- Convert the remaining SurfStat functions to match their Python counterparts.

### CODE REVIEW

**Comment by sheyma** [comment]
cool!

**Comment by sheyma** [comment]
I rebased this PR on master, because, git complained that this branch is out-of-date. After rebasing, Lint started failing.

It might help, if you 1) merge PR #110 into master, since Lint was fixed there, & 2) rebase PR #112 on master.

**Comment by ReinderVosDeWael** [comment]
I suspect you accidentally rebased it on an old master - the lint is already fixed in master. Anyway, I merged master into this branch and lint looks like its succeeding.

**Comment by sheyma** [comment]
yeap! that was my mistake. I was one commit behind the master.

**Pull request merged**
