### PR TITLE
Datagen

### PR DESCRIPTION
**Pull request by sheyma**
Hi,
here is the first dummy version of a test-generator code. 

Usage:
`$ pytest test_linear_model.py 
`

It is calling [datagen_linear_model.py](https://github.com/MICA-MNI/BrainStat/tree/datagen/brainstat/tests) beforehand, so that the necessary test data is generated.

Advantages:

- having only one dataset [thickness_n10.h5](https://github.com/MICA-MNI/BrainStat/blob/datagen/extern/test-data/thickness_n10.h5), the real data relevant part is done. And it is only 2.5 MB.
- numpy random seed is now used to fix the randomly generated data the same.

To-do:
- maybe adding somewhere in config.py to skip test generator, if data was already generated.

Question:
- Which file format we want? *h5 or *.pkl? 

Review is appreciated before adjusting it to other tests.

Cheers!

### CODE REVIEW

**Comment by ReinderVosDeWael** [comment]
So most of these comments I made on a private Slack message, but I'll just put there here along with other comments in case others want to get involved in the discussion.

New comments:
Between .h5 and .pkl, I don't have a strong preference. .pkl would be easier for me as pickle reading is already implemented in the MATLAB unit tests (#107). But if there's good arguments in favour of h5 then h5 is fine too. 

Old comments:
I'd refactor the code to put repetitive sections of code into centralized functions. This'll 1) make it easier to add/remove tests, and 2) its easier to read and maintain such code e.g. when we change the input parameters for `linear_model` then we don't have to adjust that in 15 different locations, 3) allow us to reuse code across test generations e.g. the `dict2pkl` function listed below could apply to all data generation functions.

As an example, unit tests 1-3 could be refactored to the code below. All the unit tests based on random data could be added by simply expanding`Y_dim`, `M_dim` and potentially the `zip()`. I used pickle in this example, but as mentioned above, I don't particularly care whether we use .pkl or .h5.
```
import numpy as np
import pickle
from brainstat.stats.SLM import SLM
from brainstat.stats.terms import Term

def get_linmod_output(Y, M):
    """ Runs linmod and returns all relevant output. """
    slm = SLM(M, Term(1))
    slm.linear_model(Y)
    keys = ['cluster_threshold', 'coef', 'df', 'drlim', 'niter',
          'resl', 'SSE', 'thetalim', 'X', 'tri']
    D = {}
    for key in keys:
        if getattr(slm, key) is not None:
            D[key] = getattr(slm, key)
    return D
    
def dict2pkl(D, filename):
    """ Converts a dictionary to a .pkl.gz file """
    ##TODO: Expand with file compression.
    if not filename.endswith('.pkl'):
        raise ValueError('filename must end with .pkl')
    with open(filename, 'wb') as pkl_file:
        pickle.dump(D, pkl_file)
        
def generate_random_test_data(Y_dim, M_dim, filename, seed=0, M_term=False, add_intercept=True):
    """ Generate random test datasets. """
    np.random.seed(seed=seed)
    Y = np.random.random_sample(Y_dim)
    M = np.random.random_sample(M_dim)
    if add_intercept:
        M = np.concatenate((np.ones((M_dim[0],1)), M), axis=1)
    if M_term:
        M = Term(M)
    linmod_output = get_linmod_output(Y, M)
    dict2pkl(linmod_output, filename)
    
Y_dim = ((43,43),(62,7), (54,64,76))
M_dim = ((43,43),(62,92), (54,2))
base_filename = '/Users/reinder/Desktop/test_output_'
test_nr = 0

for (Y, M) in zip(Y_dim, M_dim):
    filename = base_filename + str(test_nr).zfill(2) + '.pkl'
    generate_random_test_data(Y, M, filename, seed=test_nr)
    test_nr += 1
```

**Comment by ReinderVosDeWael** [comment]
Also see #83 for the lint fail.

**Comment by sheyma** [comment]
yo! ... will continue on it.

**Comment by sheyma** [comment]
Hi, 

- *h5 format is replaced back to *pkl
- data generation preserved in conftest. Adding [cache file](https://github.com/MICA-MNI/BrainStat/blob/datagen/brainstat/tests/datagen_linear_model.py#L91-L93), data is not generated if it exists.
- small functions added for **1.** random data generation and saving it as *IN* pickle, **2.** running  slm.linear_model and saving it as *OUT* pickle

Up: Having only [thickness_n10.pkl](https://github.com/MICA-MNI/BrainStat/blob/test-data/extern/test-data/thickness_n10.pkl) in our package, all test data for linmod can be quickly generated. This way, we can also completely remove **extern** later.

Down: Usage of the file [xlinmode_generated](https://github.com/MICA-MNI/BrainStat/blob/datagen/brainstat/tests/datagen_linear_model.py#L91)  would not yet reflect any further edits in data generation function. Dirty-way of getting around it: delete it, if you want to edit data generation function and re-run it.

Cheers!

**Comment by ReinderVosDeWael** [comment]
Heya,

To clarify my comment on the data generation from earlier: I strongly advise against generating data in confttest.py as that will remove any sort of gold standard for our modifications.

Consider the following: I make a change to the Python code where I add +5 to the degrees of freedom. Clearly this is a mistake that should be caught by our unit tests. However, if we generate the test data from the same code that we are testing, then this degrees of freedom bug is placed into our now-bugged test data. Afterwards we test, with the bugged code, whether our output is the same as our bugged test data. Because the code used to generate both is identical we indeed get a passing test. 

With the data on the extern we will always know whether our changes affect the output. If a change affecting the output is desired, then we regenerate the data at that point.

**Comment by ReinderVosDeWael** [comment]
To add to that: caching doesn't resolve the above issue; our continuous integration won't store these files i.e. will regenerate them on every run. For local runs this means that different machines may be running with different test data.

**Comment by sheyma** [comment]
Alright, good points above!

Now, **datagen_linear_model.py** is decoupled from **conftest.py**, and therefore from the tests.

BrainStat/extern/test-data/ is updated by adding xlinmod_\*\.pkl, that were generated by **datagen_linear_model.py**. We could consider later removing linmod_\*\.pkl, if this PR here is merged into master.

Best.

**Comment by ReinderVosDeWael** [comment]
This is starting to look really nice :). Perhaps this would be a good moment to merge #107 so we can double check the changes made here with MATLAB unit test. If the MATLAB unit tests pass on the data generated here then things should be OK.

**Comment by sheyma** [comment]
ok, thanks for Lint Fix.

**Comment by ReinderVosDeWael** [comment]
Before we merge this, we may want to resolve #123 in this PR.

**Pull request merged**
