### PR TITLE
Vis

### PR DESCRIPTION
**Pull request by sheyma**
- plots brain surfaces using 'coords' and 'tri' info (for left and right hemispheres)
- plots surfstat-data along these surfaces
- fsaverage5 surface data added

example usage:

```
from nibabel.freesurfer.io import read_geometry
from nilearn.plotting.surf_plotting import load_surf_data
from nilearn.plotting.surf_plotting import load_surf_mesh

SW_surf_L = read_geometry('fsaverage5/lh.white')
SW_surf_R = read_geometry('fsaverage5/rh.white')

SW = {}
SW['coords'] = np.concatenate((SW_surf_L[0], SW_surf_R[0]))
SW['tri']    = np.concatenate((SW_surf_L[1], SW_surf_R[1]))


Fs_Mesh_L = read_geometry('fsaverage5/lh.pial')
Fs_Mesh_R = read_geometry('fsaverage5/rh.pial')

Fs_Bg_Map_L  = load_surf_data('fsaverage5/lh.sulc')
Fs_Bg_Map_R = load_surf_data('fsaverage5/rh.sulc')


SURF_MESH = {}
SURF_MESH['coords'] = np.concatenate((Fs_Mesh_L[0], Fs_Mesh_R[0]))
SURF_MESH['tri']    = np.concatenate((Fs_Mesh_L[1], Fs_Mesh_R[1]))

BG_MAP = np.concatenate((Fs_Bg_Map_L, Fs_Bg_Map_R))

STAT_MAP = np.random.rand(10242*2,)

Mask_Left  = nb.freesurfer.io.read_label('fsaverage5/lh.cortex.label')
Mask_Right = nb.freesurfer.io.read_label('fsaverage5/rh.cortex.label')

MASK = np.concatenate((Mask_Left,  10242 + Mask_Right))


fig01 = surfaces.plot_surfstat(SW, BG_MAP)

fig02 = surfaces.plot_surfstat(SURF_MESH, BG_MAP)

fig03 = surfaces.plot_surfstat(SURF_MESH, BG_MAP,
                                STAT_MAP, mask = MASK)
```

white_surf

pial_surf

pial_surf_randomstat

- advantage compared to `brainspace`: any version of fssurface data can be plotted (lower or higher resolution)
- disadvantage: slower
- to-do : colorbar option and thresholding

### CODE REVIEW

**Comment by sheyma** [comment]
... btw, open for any naming suggestions for plotting functions ;)

**Comment by sheyma** [comment]
testing with thickness tutorial data 
surfstat_thickness

**Comment by sheyma** [comment]
Hi, 
this is not a must PR from my side.
I find it nice to have a small visualization piece in brainstat independent of brainspace.
However, if it is decided to keep brainsapce vizualisation, it is also perfectly fine to go with that.
Best.

**Comment by ReinderVosDeWael** [comment]
"advantage compared to brainspace: any version of fssurface data can be plotted (lower or higher resolution)" this is incorrect; the BrainSpace implementation accepts any surface. So at this stage I'm not entirely sure what the advantage of this implementation is over the already existing visualization tools. 

With that in mind I think we may want to step back and consider what we want from a visualization tool that _isnt_ already covered by either BrainSpace or Nilearn. 

One option would be to turn the slm into a class with its own plotting function allowing for quick plotting of the t-values, thresholded values at some alpha etc...

**Pull request closed without merging**
